name: "Hand Gesture Recognition"
version: "1.1.1"
image: "ghcr.io/potrgani/handgesturerecognition"
slug: "hand-gesture-recognition"
description: "Recognize hand gestures using MediaPipe and publish them to MQTT."
url: "https://github.com/potrgani/hand-gesture-recognition-ha-addon/tree/main"
startup: application
boot: auto
host_network: true  # Use host network mode
ingress_panel: true
docker:
  image: your-addon-image:latest
  privileged: true
  ports:
    - "1883:1883"
  restart: always
  network_mode: host  # Use host network mode
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
  - ssl

options:
  rtsp_url: null  
  mqtt_host: null
  mqtt_port: 1883
  mqtt_username: null
  mqtt_password: null
  mqtt_topic: "hand_gesture_status"
  reset_hand_status_time: 10
  
schema:
  rtsp_url: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  mqtt_topic: str
  reset_hand_status_time: int
